# Generated by Django 5.1.8

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_data", models.JSONField()),
                ("output", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("condition", models.JSONField()),
                ("action", models.CharField(max_length=255)),
                ("priority", models.PositiveIntegerField(db_index=True)),
            ],
            options={
                "ordering": ["-priority", "id"],
                "indexes": [models.Index(fields=["priority", "id"], name="rule_priority_idx")],
            },
        ),
    ]
